# Generated by Django 3.0.7 on 2020-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_inventory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='raw_material')),
            ],
        ),
    ]
