# Generated by Django 3.0.7 on 2020-08-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200825_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raw_Material',
        ),
    ]
